apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hey-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.3.2
    helm:
      values: |
        name: hey-soh-re
        replicaCount: 2
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: hey-soh-re
        virtualService:
          hosts:
            - "hey.soh.re"
        image:
          repository: zot.soh.re
          name: hey.soh.re
          tag: "v1.0.6"
          pullPolicy: IfNotPresent

  destination:
    name: k3s.soh.re
    namespace: hey-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
