apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hey-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 1.0.1
  destination:
    name: in-cluster
    namespace: hey-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

