apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hey-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.3.1
    helm:
      values: |
        name: hey-soh-re
        replicaCount: 2

  destination:
    name: in-cluster
    namespace: hey-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
