apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jmainguy-com
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.3.2
    helm:
      values: |
        name: jmainguy
        replicaCount: 1
        image:
          name: autoweb
          tag: v1.0.0
          pullPolicy: "Always"
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: jmainguy

        virtualService: 
          hosts:
            - "jmainguy.com"
            - "www.jmainguy.com"
          redirectToPrimary: true
        env:
          REPO_URL: "https://github.com/jmainguy/jmainguy.com"

  destination:
    name: k3s.soh.re
    namespace: jmainguy-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

