apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.3.2
    helm:
      values: |
        name: nextcloud
        replicaCount: 1
        image:
          name: nextcloud
          repository: docker.io
          tag: 30
          pullPolicy: "Always"
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: jmainguy-com
        virtualService: 
          hosts:
            - "nextcloud.soh.re"
        pvc:
          enabled: true
          mountPath: /var/www/html
          size: "80Gi"
        postgres:
          enabled: true
          name: postgres-cluster
          instances: 2
          storage:
            size: 10Gi
          bootstrap:
            initdb:
              database: nextcloud
              owner: nextcloud

  destination:
    name: in-cluster
    namespace: nextcloud-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

