apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soh-re
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Standouthost/helm-charts
    targetRevision: main
    path: sohre
  destination:
    name: in-cluster
    namespace: soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

