apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.3.2
    helm:
      values: |
        name: spam-soh-re
        replicaCount: 2
        image:
          name: wp-spam
          repository: zot.soh.re
          tag: v1.0.7
          pullPolicy: "Always"
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: spam-soh-re
        virtualService: 
          hosts:
            - "spam.soh.re"
        secret:
          enabled: true
          name: spam-creds

  destination:
    name: k3s.soh.re
    namespace: rightway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

