apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statuscode-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 1.0.2
    helm:
      values: |
        image:
          name: statuscode
          tag: v1.0.0
          pullPolicy: "Always"
        service:
          targetPort: 4567
        virtualService: 
          hosts:
            - "statuscode.soh.re"

  destination:
    name: in-cluster
    namespace: statuscode-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

