apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ahhc
  namespace: argocd
spec:
  project: default
  source:
    chart: wordpress
    repoURL: zot.soh.re
    targetRevision: 1.2.0
    helm:
      releaseName: ahhc
      values: |
        virtualService: 
          redirectToPrimary: true
          hosts:
            - "ahhc.org"
            - "www.ahhc.org"

  destination:
    name: k3s.soh.re
    namespace: ahhc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

