apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: berth-harborvane-io
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.4.0
    helm:
      values: |
        name: berth
        replicaCount: 3
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: berth
        virtualService:
          hosts:
            - "berth.harborvane.io"
        image:
          repository: zot.soh.re
          name: berth/server
          tag: "latest"
          pullPolicy: Always
        secret:
          enabled: true
          name: berth-secrets
        env:
          BASE_URL: "https://berth.harborvane.io"
          PORT: 8080
          UPLOAD_DIR: /data/uploads
        pvc:
          enabled: true
          size: 10Gi
          mountPath: /data
        postgres:
          enabled: true
          name: postgres-cluster
          instances: 1
          storage:
            size: 10Gi
          bootstrap:
            initdb:
              database: berth
              owner: berth

  destination:
    name: k3s.soh.re
    namespace: berth-harborvane-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
