apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-secrets-jmainguy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Standouthost/helm-charts
    targetRevision: main
    path: github-secrets
    helm:
      values: |
        clusterSecretStore:
          provider:
            github:
              appID: 2267752
              installationID: 94022774
              organization: jmainguy
              # repository is provided per-item in the top-level `repos` list
              auth:
                privateKey:
                  name: github-app-private-key
                  key: privateKey.pem

        pushSecret:
          deletionPolicy: Delete
          refreshInterval: 10m
          selectorSecretName: github-secrets
          data:
            - secretKey: DOCKER_USERNAME
              remoteKey: DOCKER_USERNAME
            - secretKey: DOCKER_PASSWORD
              remoteKey: DOCKER_PASSWORD
            - secretKey: DOCKER_USERNAME
              remoteKey: HELM_USERNAME
            - secretKey: DOCKER_PASSWORD
              remoteKey: HELM_PASSWORD
        repos:
          - ansible-playbooks
          - asciiquarium
          - autoweb
          - bak
          - bible
          - bible_databases
          - bizbuy
          - bstore
          - casecmp
          - certificatedownloader
          - cpu_eater
          - czechdns
          - dns_latency
          - docker-workflows
          - docker_images
          - docker_minecraft
          - docker_rpmbuild
          - ev1write
          - ghdefaultbranch
          - ghreport
          - ghReview
          - githubstats
          - goalie
          - Goblin
          - goboot
          - gohome
          - golang-cli-template
          - golang-workflows
          - gotosleep
          - helm-workflows
          - hey.soh.re
          - http-latency
          - httpIdle
          - httpPound
          - http_dos
          - http_whois
          - ibsdns
          - inotify-monitor
          - inotify-watch-finder
          - jbot
          - jmainguy
          - jmainguy.com
          - json-to-variables
          - k8sCapcity
          - k8sDrainReport
          - k8snodeissues
          - kibanaRefreshFields
          - kubectl-decodesecret
          - letsencryptautomation
          - madowynn
          - math-quest
          - mbp-fedora-kernel
          - mermaid
          - minecraft_bedrock
          - openshift-ansible
          - openshift-mysql
          - OpenShiftWeechat
          - patient_csv_to_xml
          - powerchord
          - ppq
          - pyHackpySlash
          - PythonScripts
          - rblack
          - rego-test-assertions
          - relevy
          - relevy-web
          - repeatafterme
          - rshell
          - runner-alarm
          - scalewatch
          - servmon
          - setup-jfrog-cli
          - shanty
          - sinatrarb-virt-manager
          - soh-router
          - soh.re
          - standouthost.com
          - statuscode
          - stockop
          - survival-game
          - tabs
          - test-json-to-variables
          - timesheets
          - ttyd
          - vpsaddict.com
          - webinfo
          - whatismyip
          - wp-spam
          - zenoss
          - hockey
          - bible-soh-re
          - isolation-proxy
  destination:
    name: k3s.soh.re
    namespace: github-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
