apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-secrets-harborvane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Standouthost/helm-charts
    targetRevision: main
    path: github-secrets
    helm:
      values: |
        clusterSecretStore:
          provider:
            github:
              appID: 2267752
              installationID: 107048772
              organization: harborvane
              # repository is provided per-item in the top-level `repos` list
              auth:
                privateKey:
                  name: github-app-private-key
                  key: privateKey.pem

        pushSecret:
          deletionPolicy: Delete
          refreshInterval: 10m
          selectorSecretName: github-secrets
          data:
            - secretKey: DOCKER_USERNAME
              remoteKey: DOCKER_USERNAME
            - secretKey: DOCKER_PASSWORD
              remoteKey: DOCKER_PASSWORD
            - secretKey: DOCKER_USERNAME
              remoteKey: HELM_USERNAME
            - secretKey: DOCKER_PASSWORD
              remoteKey: HELM_PASSWORD
        repos:
          - harborvane

  destination:
    name: k3s.soh.re
    namespace: github-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
