apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hockey-soh-re
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Standouthost/helm-charts
    targetRevision: main
    path: hockey
  destination:
    name: k3s.soh.re
    namespace: hockey-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
