apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    chart: jellyfin
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.3.0
    helm:
      values: |
        ingress:
          enabled: false
        persistence:
          media:
            storageClass: longhorn
            size: 50Gi
  destination:
    name: k3s.soh.re
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

