apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rightway
  namespace: argocd
spec:
  project: default
  source:
    chart: wordpress
    repoURL: zot.soh.re
    targetRevision: 1.2.0
    helm:
      releaseName: right
      values: |
        virtualService: 
          redirectToPrimary: true
          hosts:
            - "rightwaypropertycare.com"
            - "www.rightwaypropertycare.com"

  destination:
    name: k3s.soh.re
    namespace: rightway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

