apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 3.0.0
    helm:
      values: |
        name: transmission
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 9091
          name: transmission
        virtualService:
          hosts:
            - "transmission.jmainguy.com"
        image:
          repository: lscr.io
          name: linuxserver/transmission
          tag: "latest"
          pullPolicy: Always
        secret:
          enabled: true
          name: transmission
        persistence:
           - name: downloads
             mountPath: /downloads              # Where to mount in the container
             existingClaim: "transmission-pvc"  # Optional: name of existing PVC to use (do not create one)
           - name: config
             mountPath: /config
             size: 1Gi
           - name: watch
             mountPath: /watch
             size: 1Gi

  destination:
    name: k3s.soh.re
    namespace: transmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
