apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-application
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Standouthost/clusters.git
        revision: HEAD
        files:
          - path: "clusters/oracle-arm64-k3s/config.json"  # Targeting specific cluster
  template:
    metadata:
      name: '{{.cluster.name}}-cert-manager'  # Example: k3s-soh-re-cert-manager
    spec:
      project: default
      source:
        repoURL: https://github.com/Standouthost/helm-charts
        targetRevision: main
        path: cert-manager
        helm:
          releaseName: "cert-manager"  # Set the release name explicitly
      destination:
        name: '{{.cluster.name}}'
        namespace: cert-manager  # Namespace where resources should be deployed
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
