apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-application
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Standouthost/clusters.git
        revision: HEAD
        files:
          - path: "clusters/oracle-arm64-k3s/config.json"  # Targeting specific cluster
  template:
    metadata:
      name: '{{.cluster.name}}-external-secrets'  # Example: k3s-soh-re-external-secrets
    spec:
      project: default
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.15.1
        helm:
          releaseName: "external-secrets"  # Set the release name explicitly
      destination:
        name: '{{.cluster.name}}'
        namespace: external-secrets  # Namespace where resources should be deployed
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
