apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scalewatch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jmainguy/scalewatch/
    targetRevision: main
    path: charts/scalewatch
  destination:
    name: in-cluster
    namespace: scalewatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
