apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Standouthost/helm-charts
    targetRevision: main
    path: istio
  destination:
    name: oracle-arm64-k3s
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/failurePolicy
  - group: apps
    kind: Deployment
    name: istiod
    namespace: istio-system
    jqPathExpressions:
      - '.spec.template.spec.containers[] | select(.name=="discovery") | .env[] | select(.name=="GOMEMLIMIT")'
